@startuml
left to right direction
actor Cliente as C
actor Admin as A
actor Assinante as S
actor Avulso as V
package Schedule{
  usecase "Fazer agendamento" as UC1
  usecase "Cancelar agendamento" as UC2
  usecase "Comprar pacote" as UC3
  usecase "Cancelar pacote" as UC4
  usecase "Monitorar estoque" as UC5
  usecase "Registrar transação" as UC6
  usecase "Gerar relatório" as UC7
  usecase "Relatório clientes" as UC8
  usecase "Relatório compra-venda" as UC9
  usecase "Relatório DRE" as UC10
}
C <|-left- S
C <|-left- V
A --> UC1
A --> UC2
A --> UC5
A --> UC6
A --> UC7
S --> UC3
S --> UC4
C --> UC1
C --> UC2
(UC7) .down.> (UC8)
(UC7) .down.> (UC9)
(UC7) .down.> (UC10)
@enduml
