@startuml
left to right direction
actor Cliente as C
actor Dono as D
actor Funcionário as F
actor Recepcionista as R
actor Admin as A
package Schedule{
  usecase "Fazer agendamento" as UC1
  usecase "Cancelar agendamento" as UC2
  usecase "Comprar pacote" as UC3
  usecase "Cancelar pacote" as UC4
  usecase "Monitorar estoque" as UC5
  usecase "Registrar transação" as UC6
  usecase "Gerar relatório" as UC7
  usecase "Relatório clientes" as UC8
  usecase "Relatório compra e venda" as UC9
  usecase "Relatório DRE" as UC10
  usecase "Relatório de pacotes" as UC11
  usecase "Registro de compras de serviços" as UC12
  usecase "Contratação de serviços" as UC13
  usecase "Relatório de usuários" as UC14
}
A -- UC12
A -- UC14
C -- UC3
C -- UC4
C -- UC1
C -- UC2
D -- UC1
D -- UC2
D -- UC5
D -- UC6
D -- UC13
D -- UC7
R -- UC1
R -- UC2
R -- UC6
R -- UC8
F -- UC5
F -- UC8

(UC7) <|-- (UC8)
(UC7) <|-- (UC9)
(UC7) <|-- (UC10)
(UC7) <|-- (UC11)
@enduml
